-- CREATING A NEW ENUM TYPE FOR USER TYPE
CREATE TYPE user_type AS ENUM('APP_USER', 'AGENT', 'MERCHANT');

-- CREATING A NEW ENUM FOR USER STATUSES
CREATE TYPE user_status AS ENUM('ACTIVE', 'INACTIVE', 'FROZEN');

-- ALTERING THE USER TYPE OF THE USERS TABLE
ALTER TABLE users
    ALTER COLUMN user_type user_type DEFAULT 'APP_USER';
    ALTER COLUMN status user_status DEFAULT 'ACTIVE';

