-- Reference/lookup data: currencies, countries (Africa-wide + the
-- international corridors ZentraPay's diaspora remittance flows touch),
-- transaction types, and provider categories.

-- ============================================================
-- CURRENCIES
-- ============================================================
INSERT INTO currencies (currency_code, currency_name, symbol, is_crypto, decimal_places) VALUES
('GHS', 'Ghanaian Cedi', 'GH₵', FALSE, 2),
('NGN', 'Nigerian Naira', '₦', FALSE, 2),
('KES', 'Kenyan Shilling', 'KSh', FALSE, 2),
('ZAR', 'South African Rand', 'R', FALSE, 2),
('UGX', 'Ugandan Shilling', 'USh', FALSE, 0),
('TZS', 'Tanzanian Shilling', 'TSh', FALSE, 2),
('RWF', 'Rwandan Franc', 'FRw', FALSE, 0),
('ETB', 'Ethiopian Birr', 'Br', FALSE, 2),
('EGP', 'Egyptian Pound', 'E£', FALSE, 2),
('MAD', 'Moroccan Dirham', 'DH', FALSE, 2),
('XOF', 'West African CFA Franc', 'CFA', FALSE, 0),
('XAF', 'Central African CFA Franc', 'FCFA', FALSE, 0),
('ZMW', 'Zambian Kwacha', 'ZK', FALSE, 2),
('BWP', 'Botswana Pula', 'P', FALSE, 2),
('MZN', 'Mozambican Metical', 'MT', FALSE, 2),
('AOA', 'Angolan Kwanza', 'Kz', FALSE, 2),
('SLL', 'Sierra Leonean Leone', 'Le', FALSE, 2),
('LRD', 'Liberian Dollar', 'L$', FALSE, 2),
('GMD', 'Gambian Dalasi', 'D', FALSE, 2),
('GNF', 'Guinean Franc', 'FG', FALSE, 0),
('MWK', 'Malawian Kwacha', 'MK', FALSE, 2),
('ZWL', 'Zimbabwean Dollar', 'Z$', FALSE, 2),
('NAD', 'Namibian Dollar', 'N$', FALSE, 2),
('CDF', 'Congolese Franc', 'FC', FALSE, 2),
('SDG', 'Sudanese Pound', 'SDG', FALSE, 2),
('SSP', 'South Sudanese Pound', 'SSP', FALSE, 2),
('SOS', 'Somali Shilling', 'Sh', FALSE, 2),
('ERN', 'Eritrean Nakfa', 'Nfk', FALSE, 2),
('DJF', 'Djiboutian Franc', 'Fdj', FALSE, 0),
('BIF', 'Burundian Franc', 'FBu', FALSE, 0),
('LSL', 'Lesotho Loti', 'L', FALSE, 2),
('SZL', 'Eswatini Lilangeni', 'E', FALSE, 2),
('MGA', 'Malagasy Ariary', 'Ar', FALSE, 2),
('MUR', 'Mauritian Rupee', '₨', FALSE, 2),
('SCR', 'Seychellois Rupee', '₨', FALSE, 2),
('CVE', 'Cape Verdean Escudo', '$', FALSE, 2),
('TND', 'Tunisian Dinar', 'DT', FALSE, 3),
('DZD', 'Algerian Dinar', 'DA', FALSE, 2),
('LYD', 'Libyan Dinar', 'LD', FALSE, 3),
('MRU', 'Mauritanian Ouguiya', 'UM', FALSE, 2),
('STN', 'São Tomé and Príncipe Dobra', 'Db', FALSE, 2),
('KMF', 'Comorian Franc', 'CF', FALSE, 0),
('USD', 'US Dollar', '$', FALSE, 2),
('GBP', 'British Pound', '£', FALSE, 2),
('EUR', 'Euro', '€', FALSE, 2),
('BTC', 'Bitcoin', '₿', TRUE, 8),
('ETH', 'Ethereum', 'Ξ', TRUE, 8),
('USDT', 'Tether', '₮', TRUE, 6);

-- ============================================================
-- COUNTRIES (54 African countries + international corridors)
-- ============================================================
INSERT INTO countries (country_code, iso3_code, country_name, dial_code, default_currency_code, region) VALUES
('GH', 'GHA', 'Ghana', '+233', 'GHS', 'West Africa'),
('NG', 'NGA', 'Nigeria', '+234', 'NGN', 'West Africa'),
('KE', 'KEN', 'Kenya', '+254', 'KES', 'East Africa'),
('ZA', 'ZAF', 'South Africa', '+27', 'ZAR', 'Southern Africa'),
('UG', 'UGA', 'Uganda', '+256', 'UGX', 'East Africa'),
('TZ', 'TZA', 'Tanzania', '+255', 'TZS', 'East Africa'),
('RW', 'RWA', 'Rwanda', '+250', 'RWF', 'East Africa'),
('ET', 'ETH', 'Ethiopia', '+251', 'ETB', 'East Africa'),
('EG', 'EGY', 'Egypt', '+20', 'EGP', 'North Africa'),
('MA', 'MAR', 'Morocco', '+212', 'MAD', 'North Africa'),
('CI', 'CIV', 'Côte d''Ivoire', '+225', 'XOF', 'West Africa'),
('SN', 'SEN', 'Senegal', '+221', 'XOF', 'West Africa'),
('TG', 'TGO', 'Togo', '+228', 'XOF', 'West Africa'),
('BJ', 'BEN', 'Benin', '+229', 'XOF', 'West Africa'),
('BF', 'BFA', 'Burkina Faso', '+226', 'XOF', 'West Africa'),
('ML', 'MLI', 'Mali', '+223', 'XOF', 'West Africa'),
('NE', 'NER', 'Niger', '+227', 'XOF', 'West Africa'),
('GW', 'GNB', 'Guinea-Bissau', '+245', 'XOF', 'West Africa'),
('CM', 'CMR', 'Cameroon', '+237', 'XAF', 'Central Africa'),
('GA', 'GAB', 'Gabon', '+241', 'XAF', 'Central Africa'),
('TD', 'TCD', 'Chad', '+235', 'XAF', 'Central Africa'),
('CG', 'COG', 'Congo (Republic)', '+242', 'XAF', 'Central Africa'),
('CF', 'CAF', 'Central African Republic', '+236', 'XAF', 'Central Africa'),
('GQ', 'GNQ', 'Equatorial Guinea', '+240', 'XAF', 'Central Africa'),
('ZM', 'ZMB', 'Zambia', '+260', 'ZMW', 'Southern Africa'),
('BW', 'BWA', 'Botswana', '+267', 'BWP', 'Southern Africa'),
('MZ', 'MOZ', 'Mozambique', '+258', 'MZN', 'Southern Africa'),
('AO', 'AGO', 'Angola', '+244', 'AOA', 'Central Africa'),
('SL', 'SLE', 'Sierra Leone', '+232', 'SLL', 'West Africa'),
('LR', 'LBR', 'Liberia', '+231', 'LRD', 'West Africa'),
('GM', 'GMB', 'Gambia', '+220', 'GMD', 'West Africa'),
('GN', 'GIN', 'Guinea', '+224', 'GNF', 'West Africa'),
('MW', 'MWI', 'Malawi', '+265', 'MWK', 'Southern Africa'),
('ZW', 'ZWE', 'Zimbabwe', '+263', 'ZWL', 'Southern Africa'),
('NA', 'NAM', 'Namibia', '+264', 'NAD', 'Southern Africa'),
('CD', 'COD', 'DR Congo', '+243', 'CDF', 'Central Africa'),
('SD', 'SDN', 'Sudan', '+249', 'SDG', 'North Africa'),
('SS', 'SSD', 'South Sudan', '+211', 'SSP', 'East Africa'),
('SO', 'SOM', 'Somalia', '+252', 'SOS', 'East Africa'),
('ER', 'ERI', 'Eritrea', '+291', 'ERN', 'East Africa'),
('DJ', 'DJI', 'Djibouti', '+253', 'DJF', 'East Africa'),
('BI', 'BDI', 'Burundi', '+257', 'BIF', 'East Africa'),
('LS', 'LSO', 'Lesotho', '+266', 'LSL', 'Southern Africa'),
('SZ', 'SWZ', 'Eswatini', '+268', 'SZL', 'Southern Africa'),
('MG', 'MDG', 'Madagascar', '+261', 'MGA', 'East Africa'),
('MU', 'MUS', 'Mauritius', '+230', 'MUR', 'East Africa'),
('SC', 'SYC', 'Seychelles', '+248', 'SCR', 'East Africa'),
('CV', 'CPV', 'Cape Verde', '+238', 'CVE', 'West Africa'),
('TN', 'TUN', 'Tunisia', '+216', 'TND', 'North Africa'),
('DZ', 'DZA', 'Algeria', '+213', 'DZD', 'North Africa'),
('LY', 'LBY', 'Libya', '+218', 'LYD', 'North Africa'),
('MR', 'MRT', 'Mauritania', '+222', 'MRU', 'West Africa'),
('ST', 'STP', 'São Tomé and Príncipe', '+239', 'STN', 'Central Africa'),
('KM', 'COM', 'Comoros', '+269', 'KMF', 'East Africa'),
('US', 'USA', 'United States', '+1', 'USD', 'International'),
('GB', 'GBR', 'United Kingdom', '+44', 'GBP', 'International');

-- ============================================================
-- TRANSACTION TYPES
-- ============================================================
INSERT INTO transaction_types (type_code, description, is_credit) VALUES
('WALLET_FUNDING', 'Funds added to a wallet from an external source', TRUE),
('TRANSFER_INTERNAL', 'Wallet-to-wallet transfer between app users', FALSE),
('TRANSFER_EXTERNAL', 'Disbursement to an external bank/mobile money account', FALSE),
('BILL_PAYMENT', 'Payment to a bill provider (utility, TV, etc.)', FALSE),
('SAVINGS_DEPOSIT', 'Funds moved from a wallet into a savings account', FALSE),
('SAVINGS_WITHDRAWAL', 'Funds moved from a savings account back to a wallet', TRUE),
('LOAN_DISBURSEMENT', 'Loan principal credited to a wallet', TRUE),
('LOAN_REPAYMENT', 'Loan repayment debited from a wallet', FALSE),
('INVESTMENT_BUY', 'Funds committed to an investment position', FALSE),
('INVESTMENT_SELL', 'Proceeds from closing an investment position', TRUE),
('REMITTANCE_SEND', 'Cross-border remittance sent', FALSE),
('CARD_PAYMENT', 'Payment made using a virtual/physical card', FALSE),
('REWARD_CREDIT', 'Cashback/reward credited to a wallet', TRUE),
('REFUND', 'Reversed/refunded transaction', TRUE);

-- ============================================================
-- PROVIDER CATEGORIES
-- ============================================================
INSERT INTO provider_categories (category_code, category_name) VALUES
('UTILITY', 'Electricity & Water'),
('AIRTIME', 'Airtime & Mobile Data'),
('TV_SUBSCRIPTION', 'TV Subscription'),
('INTERNET', 'Internet & Broadband'),
('INSURANCE', 'Insurance'),
('GOVERNMENT', 'Government Services'),
('TRANSPORT', 'Transport & Toll'),
('EDUCATION', 'Education & School Fees'),
('HEALTH', 'Health & Medical'),
('ENTERTAINMENT', 'Entertainment & Ticketing'),
('MERCHANT_GENERAL', 'General Merchant'),
('OTHER', 'Other');
