package com.zentrapay_application.zentrapay_spring_boot_layer.modules.payments.dtos;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

import java.math.BigDecimal;

/**
 * Nested payment details payload mirroring the Node.js layer's {@code paymentDetails} object.
 * <p>
 * Represents the financial specifics of a disbursement: amount, currencies,
 * destination channel, and a unique reference generated by the Node.js layer.
 */
public record PaymentRequestDetailsDTO(

        @NotNull(message = "Amount is required")
        @Positive(message = "Amount must be positive")
        BigDecimal amount,

        @NotNull(message = "Source currency is required")
        String sourceCurrency,

        String destinationCurrency,

        boolean isInternational,

        String destinationType,

        String narration,

        String reference

) {
}
